---
title: "Homework 2"
author: "Chen Chang"
date: "September 29, 2015"
output: html_document
---

I've included a header so that when you render the Rmarkdown document in RStudio
 it knows what kind of document to create, and includes some extra information 
 about the document.  


### Homework Sep.29
========================================================

#### Part 1 - Make these plots!

```{r}
library(gapminder)
library(ggplot2)
library(dplyr)
```

1)

```{r}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, colour = continent, shape = continent)) + 
geom_point()

# You forgot shape.
```

2)

```{r}
ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp, colour = continent, shape = continent)) + 
geom_point()

# An alternative is to change the scale of the x axis:
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, colour = continent, shape = continent)) + 
  geom_point() +
  scale_x_log10()
```

3)

```{r}
ggplot(data = gapminder, aes(x = log(gdpPercap), y = lifeExp)) + 
geom_point(aes(colour=continent, shape = continent)) +  
geom_smooth(method='lm') 

# JD: put different layers on new lines - makes it easier to read

```

4)

```{r}
ggplot(data = gapminder, aes(x = lifeExp, fill = continent)) + 
  geom_density(alpha = 0.5) + 
  facet_wrap(~ year)
```

5)

```{r}
ggplot(data = gapminder, aes(x = continent, y = lifeExp, colour = continent)) + 
  geom_boxplot() + 
  facet_wrap(~ year) + 
  scale_x_discrete(breaks=c("Africa", "Americas", "Asia", "Europe", "Oceania"), 
                   labels=c("Af", "Am", "As", "Eu", "Oc"))

# Nice. Another way you could have done this was 
ggplot(data = gapminder, aes(x = continent, y = lifeExp, colour = continent)) + 
  geom_boxplot() + 
  facet_wrap(~ year) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

#### Part 2 Make these plots and then some!

6)

```{r}
ggplot(gapminder, aes(x = lifeExp, fill = continent)) + 
  geom_density(alpha=0.5)
```

7)

```{r}
Asia <- gapminder %>%
  filter(continent %in% 'Asia') 
mean_lifeExp <- mean(Asia$lifeExp)

ggplot(Asia, aes(x = lifeExp, fill = continent)) + geom_density(alpha = .8) + 
  geom_vline(xintercept = mean_lifeExp) + ggtitle('Life expectancy in Asia')

# JD: It can be preferable when the object is small, to create the data subset 
# within the ggplot so that you don't end up with many little objects running 
# filling up your workspace. You can also just calculate the mean in ggplot if 
# you'd like:

ggplot(filter(gapminder, lifeExp, continent), aes(x = lifeExp, fill = continent)) + 
  geom_density(alpha = 0.5) + 
  geom_vline(xintercept = mean(lifeExp))

```

8)

```{r}
# a.
lifeExp_Cont <- group_by(gapminder,continent) %>%
  summarise(mean_lifeExp = mean(lifeExp))

# b.
ggplot(gapminder, aes(x = lifeExp, fill = continent)) + 
  geom_density() + 
  facet_wrap( ~ continent) + 
  geom_vline(data = lifeExp_Cont, aes(xintercept = c(48.87,64.59,60.06, 71.90, 74.33)))

# bbb on class
  ggplot(gapminder, aes(x = lifeExp, fill = continent)) +
    geom_density (alpha = 0.5) + 
    geom_vline(data = lifeExp_Cont, aes(xintercept = mean_lifeExp)) +
    facet_wrap( ~ continent)
    
```

#### Part 3 Trouble shooting

```{r}
setwd("/Users/cc/Desktop/R00/homework")

hw_gapminder <- read.csv("./hw_gapminder.csv")

mean_lifeExp <- mean(hw_gapminder$lifeExp)

small_set <- hw_gapminder[c(1:4, 1300:1304), c(1:3)]

# What I was looking for here was the missing c():
small_set <- hw_gapminder[c(1, 2, 3, 4, 1300:1304), c('country', 'continent', 'year')]
# Doing it by position works too, but sometimes it can be easier to know what 
# columns are being selected if they're explicitly named (more important in 
# larger datasets)

mean_gdp <- mean(hw_gapminder$gdpPercap, na.rm = TRUE)

max_country <- hw_gapminder$country[which(hw_gapminder$lifeExp == max(hw_gapminder$lifeExp))]
```
